In [113]:
# New
import os

# replace with the path to your folder
path = "./BIWISubset"
txt_files = [f for f in os.listdir(path) if f.endswith('.txt')]

sort_array = []

for txt_file in txt_files:
    sort_array.append(txt_file)

sort_array.sort()


In [114]:
import numpy as np
import os

# Set the path to the folder containing the text files
folder_path = "./BIWISubset/"

# Empty array
empty_array = []
i = 0
# Loop over each file in the folder
for i in range(len(sort_array)):
    file_path = os.path.join(folder_path, sort_array[i])
    with open(file_path, "r") as f:

        # Read the last three lines of the file
        lines = f.readlines()

        for i, line in enumerate(lines):
            if "XYZ:" in line:
                xyz_index = i
                break

        next_line = lines[xyz_index].strip()
        # get the line after "XYZ:" and remove any leading/trailing whitespace
        next_line = next_line.replace("XYZ: ", "").split(",")
        # print(next_line)
        x = float(next_line[0])
        y = float(next_line[1])
        z = float(next_line[2])
        # print(f"x: {x}, y: {y}, z: {z}")

        # Store the values in an array and print the array
        empty_array.append([x, y, z])
        i = 1
print(empty_array)


[[3.8833971253815913, -3.021118096428776, 0.7440105498619943], [3.838064925996581, -2.9804891914597174, 1.2208583059252354], [4.0700480171009294, -3.6339842316187583, 0.9787322381090248], [3.9692166393793538, -3.3882888830506404, -0.48791242978769744], [4.44285319665032, -2.9988202234742496, 0.848866258386096], [4.32066056919093, -3.310140610724943, 0.8676697566890527], [4.024881019358992, -2.8419285152599074, 0.8183538522802333], [4.121268384258813, -3.4607814278267024, 0.7639122356862097], [4.004029353455398, -2.6011183948444727, 1.0355069131237762], [4.250504405428911, -3.694713242462569, 0.5300728954891055], [4.058727158099738, -3.2514276494097474, 0.6170217450460609], [3.9092815608948857, -3.1494476684280306, 0.5877861350182219], [4.131018723137216, -3.714786959314583, 0.5554403894217457], [3.805856670282321, -3.4703949821893865, 0.9506487244519845], [3.891226940856444, -3.360188860373099, 0.6199018760798937], [3.7680511865380923, -3.686252761956876, -0.06315549541512523], [4.0425

In [115]:
X = np.array(empty_array)
min_val = X.min()
max_val = X.max()
normalized_array = (X - min_val) / (max_val - min_val)
print(normalized_array)


[[0.5757024  0.51527422 0.54822655]
 [0.57530566 0.5156298  0.55239991]
 [0.57733597 0.50991042 0.55028083]
 ...
 [0.67182076 0.54297353 0.47477295]
 [0.67394447 0.52586164 0.48466424]
 [0.67641173 0.51972082 0.48987428]]


In [130]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.cm as cmx
import os

def visualize_3d_gmm(points, w, mu, stdev, export=True):
    '''
    plots points and their corresponding gmm model in 3D
    Input: 
        points: N X 3, sampled points
        w: n_gaussians, gmm weights
        mu: 3 X n_gaussians, gmm means
        stdev: 3 X n_gaussians, gmm standard deviation (assuming diagonal covariance matrix)
    Output:
        None
    '''

    n_gaussians = mu.shape[1]
    N = int(np.round(points.shape[0] / n_gaussians))
    # Visualize data
    fig = plt.figure()
    axes = fig.add_subplot(111, projection='3d')
    axes.set_xlim([0, 1])
    axes.set_ylim([0, 1])
    axes.set_zlim([0, 1])
    colors = ['orangered',
            'orange',
            'gold',
            'greenyellow',
            'turquoise',
            'cyan',
            'dodgerblue',
            'blue',
            'blueviolet',
            'fuchsia',
            'deeppink',
            'crimson']
    for i in range(n_gaussians):
        idx = range(i * N, ((i + 1) * N)-1)
        print(idx)
        axes.scatter(points[idx, 0], points[idx, 1], points[idx, 2], alpha=0.3, c=colors[i], s=100, marker='.')

    plt.title('3D GMM')
    axes.set_xlabel('X')
    axes.set_ylabel('Y')
    axes.set_zlabel('Z')
    axes.view_init(elev=45, azim=180+45)
    
    if export:
        if not os.path.exists('images/'): os.mkdir('images/')
        plt.savefig('images/3D_GMM_demonstration.png', dpi=100, format='png')
    plt.show()

import numpy as np
from sklearn.mixture import GaussianMixture

#fit the gaussian model
gmm = GaussianMixture(n_components=11, covariance_type='diag')
print(gmm.fit(X))

visualize_3d_gmm(normalized_array, gmm.weights_, gmm.means_.T, np.sqrt(gmm.covariances_).T)
    # print(X[4][2])

GaussianMixture(covariance_type='diag', n_components=11)
